spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  config:
    import: optional:file:.env[.properties]


weather-stack:
  api-url: http://api.weatherstack.com/current
  api-key: ${API_KEY:default}

resilience4j:
  ratelimiter:
    instances:
      basic:
        limit-for-period: 10
        limit-refresh-period: 1m
        timeout-duration: 10s
management:
  endpoint:
    web:
      exposure:
        include:
          - "*"
          - prometheus.yml





